version: 19.00.{build}

image: Visual Studio 2017

init:
  - set SVZSRC=7z1900-src.7z
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cl

before_build:
  - curl -fsLO https://www.7-zip.org/a/%SVZSRC%
  - 7z x -bd -osrc %SVZSRC%

build_script:
  - cd src\CPP\7zip\Bundles\Alone
  - nmake CPU=AMD64 NEW_COMPILER=1 MY_STATIC_LINK=1
  - copy x64\7za.exe ..\..\..\..\..\

after_build:
  - cd ..\..\..\..\..
  - sha256sum 7za.exe > 7za.exe.sha256

artifacts:
  - path: 7za.exe
  - path: 7za.exe.sha256

deploy:
  tag: 19.00-vs2017
  release: 7za.exe
  description: '7za.exe 19.00 (Visual Studio 2017)'
  provider: GitHub
  auth_token:
    secure: M8UHMmf7TSJxv+Q94NpkLaF4p6k4TUWoRd52Md9HQ4zvpEg3Yo+NZrgZFp4cMKNl
  artifact: 7za.*
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
